name: 'Configure and build PluginTemplate'

on:
  workflow_call:
    inputs: # Note these need to be manually synched with template
      project_name:
        required: false
        type: string
        default: "New Plugin"
      project_slug:
        required: false
        type: string
        default: "new_plugin"
      nwx_cmake:
        required: false
        type: boolean
        default: true
    secrets:
      CONTAINER_REPO_TOKEN:
        required: true
jobs:
  Test-Cookiecutter:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/nwchemex/nwx_buildenv:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install cookeicutter
        run: |
          pip install cookiecutter
        shell: bash
      - name: Install ase
        run: pip install ase
      - name: Install NWChem
        run: sudo apt-get install -y nwchem    
      - name: Install Zip
        run: |
          apt-get update && apt-get install -y zip
        shell: bash
   
      - name: Zip current state
        run: |
          # From the Cookiecutter docs
          (SOURCE_DIR=$(basename $PWD) ZIP=cookiecutter.zip && 
          pushd .. &&
          zip -r $ZIP $SOURCE_DIR --exclude $SOURCE_DIR/$ZIP --quiet &&
          mv $ZIP $SOURCE_DIR/$ZIP &&
          popd &&
          echo  "Cookiecutter full path: $PWD/$ZIP")
        shell: bash
   
      - name: Write configure.yaml
        run: |
          echo "default_context:" > configure.yaml
          echo "  project_name: ${PROJECT_NAME}" >> configure.yaml
          echo "  project_slug: ${PROJECT_SLUG}" >> configure.yaml
          echo "  nwx_cmake: ${NWX_CMAKE}" >> configure.yaml
        shell: bash
        env:
          PROJECT_NAME: ${{ inputs.project_name }}
          PROJECT_SLUG: ${{ inputs.project_slug }}
          NWX_CMAKE: ${{ inputs.nwx_cmake }}

      - name: Test current state
        run: |       
          # Generate the template
          cookiecutter ./cookiecutter.zip --no-input --config-file configure.yaml
          cd ${PROJECT_SLUG}

          # Configure, build, and test
          cmake -Bbuild -H. \
          -DCMAKE_TOOLCHAIN_FILE=./default_toolchain.cmake \
          -DCMAKE_INSTALL_PREFIX=./install
          cmake --build build --parallel
          cd build
          ctest -VV
        shell: bash
        env:
          PROJECT_SLUG: ${{ inputs.project_slug }}
